### ISSUE TITLE
Module not found: Can't resolve 'react-hook-form-resolvers'

### ISSUE THREAD

**Issue by azizur** [react-hook-form/react-hook-form-resolvers#6]
Then following the instruction in https://github.com/react-hook-form/react-hook-form-resolvers/blob/master/README.md 

Install the module using `npm install react-hook-form-resolvers`.

Then import `yupResolver`.

`import { yupResolver } from 'react-hook-form-resolvers';`

I am getting 
`
Module not found: Can't resolve 'react-hook-form-resolvers' in '{__PATH_TO_A_REMOVED_COMPONENT__}'
`

When I look into the `node_modules/react-hook-form-resolvers` it's empty.
![Screenshot 2020-05-12 at 06 46 33](https://user-images.githubusercontent.com/114551/81642886-5ab49280-941c-11ea-85ff-c2d474034df1.png)

**Comment by bluebill1049** [comment]
hey, @azizur I haven't released an updated version just yet, expected to release a v6 RC version this week.

**Comment by AlinDev** [comment]
same issue

**Comment by azizur** [comment]
@bluebill1049 Before this get released, I was thinking what the API would be?

I have a Yup schema that uses custom validation in a nested object. The custom validation depends on [form the data being provided as context](https://github.com/jquense/yup#mixedvalidatevalue-any-options-object-promiseany-validationerror). This allows me to use the context object when validating the the object.

According to https://github.com/react-hook-form/react-hook-form/pull/1471. It seems like, you can just do as per your example on there. 
```js
import React from 'react';
import { useForm } from 'react-hook-form';
import { yupResolver } from 'react-hook-form-resolvers';

const SignupSchema = yup.object().shape({
  name: yup.string().required(),
  age: yup.number().required(),
});

const App = () => {
  const { register, handleSubmit } = useForm({
    resolver: yupResolver(SignupSchema), // yup, joi and even your own.
  });

  return (
    <>
      <form onSubmit={handleSubmit(d => console.log(d))}>
        <label>Test</label>
        <input name="test" ref={register} />
        <input type="submit" />
      </form>
    </>
  );
};
```
My question is when the resolver is called by `resolver: yupResolver(SignupSchema)`. Can we provide the form data as validation context as well?

I guess one could do 
```js
const validationConfig = {
  passDataAsContext: true // default false
};
const { register, handleSubmit } = useForm({
    resolver: yupResolver(SignupSchema, validationConfig), // yup, joi and even your own.
  });
```

Or is there a better ways to do this?

I am happy to produce a PR to help with this.

**Comment by bluebill1049** [comment]
Hey @azizur ,

Thanks for the detailed explanation above. We do pass `context` into the `resolver`. However, for those resolvers in the repo, I would treat them as a black box and you only should apply config and not with context. if you need pass data into resolver, i would do this instead


```
resolver: (data, context) => {
  if (context.xxx) {
    yupResolver(validationSchema)(data);
  } else {
    yupResolver(validationSchema)({...data, test: 'test' });
  }
}
```

**Comment by bluebill1049** [comment]
First RC version is out for both RHF and RHFR

https://github.com/react-hook-form/react-hook-form-resolvers/releases/tag/v0.0.2-rc.0

let me know how did it go. 👍

**Comment by azizur** [comment]
@bluebill1049, Not the nicest API, however this works.

```js
const { handleSubmit, register, errors, setValue, reset } = useForm({
    resolver: (data) => yupResolver(validationSchema, { abortEarly: false, context: data })(data)
  });
```

a clean API could be something like:
```js
const { handleSubmit, register, errors, setValue, reset } = useForm({
    resolver: yupResolver(validationSchema, { setValidationContext: true })
  });
```
Where `setValidationContext` can be abetter named `yupResolver`'s config option that enables config to be ` { abortEarly: false, context: data }` in https://github.com/react-hook-form/react-hook-form-resolvers/blob/master/src/yup.ts#L52-L54

The value of `setValidationContext` can be either a `boolean` or an object.
1) If the value of `setValidationContext==true` it will set the `context` property to `data` eg ` { abortEarly: false, context: data }` as per Yup `mixed.validate(value: any, options?: object)` options. see: https://github.com/jquense/yup#mixedvalidatevalue-any-options-object-promiseany-validationerror

2) If the value of `setValidationContext` is an object it will set the `context` property to that object eg ` { abortEarly: false, context:{a:'user-provided-object'} }`

```js
const { handleSubmit, register, errors, setValue, reset } = useForm({
    resolver: yupResolver(validationSchema, { setValidationContext: {a:'user-provided-object'} })
  });
```

**Comment by bluebill1049** [comment]
```
const { handleSubmit, register, errors, setValue, reset } = useForm({
  resolver: (data) => yupResolver(validationSchema, { abortEarly: false, context: data })(data)
});
```
thanks @azizur for your feedback. why not doing the following: 

```
const { handleSubmit, register, errors, setValue, reset } = useForm({
  resolver: yupResolver(validationSchema, { abortEarly: false, context: data })
});
```
