### ISSUE TITLE
yupResolver loses errors when combining nested errors

### ISSUE THREAD

**Issue by jacknewberry** [react-hook-form/react-hook-form-resolvers#9]
## Problem
The yupResolver loses some nested errors

## Background
I have a schema for validating dates. The input format is an object `{day, month, year}`. This is because my input form has three separate fields.

The intention is that when the error is due to a specific field, I can highlight that field in the UI. There are some validation conditions that apply to the whole date, and for those I will highlight all three fields.

## Details
The schema (simplified slightly):
```typescript
yup
    .object({
      day: yup
        .number()
        .max(31, "Day of birth must be in range 1-31"),
      month: yup
        .number()
        .max(12, "Month of birth must be in range 1-12"),
      year: yup
        .number()
        .required("Year of birth is required")
    })
  .test({
    name: "is-valid-date",
    message: "Please enter a valid date.",
    test: value => moment(value).isValid(),
  })
```

When the input value fails validation on both a specific field, and on the whole value, the `errors` object that I receive back contains only the outer error.

i.e. for value `{day: 1, month:999, year: 1993 }`, the resulting error from yup includes both `"Month of birth must be in range 1-12"` and `"Please enter a valid date."`
but the errors object returned by `yupResolver` only contains `"Please enter a valid date."`

## Root cause?
I think this is due to the order of the keys in the object that yup returns, and a bug in https://github.com/react-hook-form/react-hook-form/blob/V6/src/logic/transformToNestObject.test.ts.
This transform tool has unexpected behaviour depending on the order of the input.

I have demonstrated this in a PR:
https://github.com/react-hook-form/react-hook-form/pull/1722
The first test passes. The second loses information. The only difference is the ordering of keys in the input.

I am not sure if the fix should be in transformToNestObject, because that may have other dependencies.

**Comment by bluebill1049** [comment]
Thanks for the PR for the unit test. however, I suspect this is a strange use case: (at least from unit test's perspective)

```
date.month
date
```

This will not work with our `register` method. do you have a CSB for your issue?

**Comment by jacknewberry** [comment]
Thanks for you rapid reply.
I agree this probably a strange use case for `transformToNestObject`. 

I'm not sure it is unusual for yup to be used to validate objects at both an individual key level and the whole object.

I don't know what you mean by 'CSB'. Perhaps you are asking for an example of the rest of the code:

We have a clumsy but functional solution that uses `setValue` to pass the `{day. month. year}` value from a custom MultiPartDate component into react-hook-form.
I am sure there are better ways to do this, but I suspect they would still have the problem of errors being lost.

```typescript
export const Page: React.FC = () => {
  const { register, handleSubmit, errors, setValue, formState } = useForm<FormD>({
    resolver
  })

  useEffect(() => {
    register({ name: "dob" })
  }, [register])

  const setDob = (date: MultiPartDate | undefined) => {
    setValue("dob", date, formState.isSubmitted)
  }

  const submit = (values): void => {
    //...
  }

  // got to massage this
  const dobErrors = errors.dob as FieldError & { day?: FieldError, month?: FieldError, year?: FieldError }

  return (
    <form className={classes.form} onSubmit={handleSubmit(submit)}>
      <MultiPartDate onChange={setDob} errors={errors.dob} />
    </form>
  )
}


const MultiPartDate: React.FC<{
  errors: any
  onChange: (date: MultiPartDate | undefined) => void
}> = ({ onChange, error }) => {
  const classes = useStyles()
  const [day, setDay] = useState<number>(NaN)
  const [month, setMonth] = useState<number>(NaN)
  const [year, setYear] = useState<number>(NaN)

  useEffect(() => {
    onChange({ year, month, day })
  }, [day, month, year, onChange])

  ... // render the three separate fields
}
```

**Comment by bluebill1049** [comment]
sorry i meant codesandbox, so i can have a play.

**Comment by jacknewberry** [comment]
https://codesandbox.io/s/dark-firefly-h0y0x?file=/src/App.tsx

I seem to have messed up the validate-on-change somehow, but I think this captures the important bits.

If you enter a date like {day: 1, month: 99, year: 2002} I'd like to see "Month of birth must be in range 1-12".

If you comment out the yup `test` in the schema, you can get this effect, but you lose the overall validation.

**Comment by bluebill1049** [comment]
hey @jacknewberry just took a look at your example, I don't think we support such usage. you should have register 3 different inputs. 

```
useEffect(() => {
    register('dob.year')
    register('dob.month')
    register('dob.day')
  }, [register])
```

**Comment by jacknewberry** [comment]
Thank you for having a look. I think the problem of the yupResolver hiding some errors still occurs when three inputs are registered.

Here I have changed the example to use `register` on each field:
https://codesandbox.io/s/proud-butterfly-5xh1u?file=/src/App.tsx

Uncommenting the yup schema `test` still causes the specific month error to be lost.

**Comment by bluebill1049** [comment]
> Thank you for having a look. I think the problem of the yupResolver hiding some errors still occurs when three inputs are registered.
> 
> Here I have changed the example to use `register` on each field:
> https://codesandbox.io/s/proud-butterfly-5xh1u?file=/src/App.tsx
> 
> Uncommenting the yup schema `test` still causes the specific month error to be lost.

The reason because there is no such field on the screen named as `dob`, so solutions

1. use `trigger` to `trigger('dob')`
2. build a custom component which contains those three inputs and wrapper with `Controllers` and register as `dob`

**Comment by jacknewberry** [comment]
Ok. I'll look into those options.
Thank you.
